### ISSUE TITLE
Write up instructions for FDA on how to make our submission package executable

### ISSUE THREAD

**Issue by thomas-neitmann** [RConsortium/submissions-pilot3-adam#17] opened 2022-11-11 06:19 UTC

**Comment by robertdevine** [comment] 2022-11-13 18:02
Highly recommended @thomas-neitmann to consult with Pilot2 Team Leadership. The Pilot2 instructions for FDA execution are excellent and provide a roadmap/template for developing the Pilot3 instructions for FDA execution. Thanks.

**Comment by laxamanaj** [comment] 2022-11-23 19:14
I quickly chatted with Ning off-line and she provided us the ADRG used to submit Pilot 2 to the FDA, which may have this info you're referring to @robertdevine : https://github.com/RConsortium/submissions-pilot2-to-fda/blob/main/m5/datasets/rconsortiumpilot2/analysis/adam/datasets/adrg.pdf

**Comment by laxamanaj** [comment] 2022-11-27 22:16
Hi, @thomas-neitmann and @robertdevine .  Thanks again for pointing me to the Pilot 2 team repos.  I was able to read through their ADRG to get a sense of the set up and steps to execution of their package to run the app.  I took the same concepts and updated the instruction and text to apply to Pilot 3 leading to the execution of the R programs to reproduce the ADaM datasets for our pilot.  In this attached document, this is a 'proposal' I've written up to help detail some of these steps to execute Pilot 3.  This will also help support updates re: Pilot 3 in our next RConsortium meeting as it was requested by a FDA staff to come up with such proposal by this week's meeting.  This might be a new request as I didn't see such proposals in the repos of Pilot 1 or Pilot 2 (unless I've overlooked it).  In any case, I hope this proposal meets their request for this Friday's meeting.  As you can still see, I could use some feedback and updates from either of you before then.  Please let me know if you have any questions.  

In the meeting, I'll mention that the information in this proposal will eventually be copied over to the ADRG / program toc upon our initial Pilot 3 eCTD submission to the FDA with further details as needed to successfully unpack and execute the Pilot 3 ADaM R programs.


[pilot3-adam-fda-execution-proposal.docx](https://github.com/RConsortium/submissions-pilot3-adam/files/10099298/pilot3-adam-fda-execution-proposal.docx)

[pilot3-adam-fda-execution-proposal.pdf](https://github.com/RConsortium/submissions-pilot3-adam/files/10099299/pilot3-adam-fda-execution-proposal.pdf)

**Comment by laxamanaj** [comment] 2022-11-28 22:08
Update.  Feedback from Ning : 

```
Ning Leng, 8 min
this looks great!
my only comment is maybe change some languages like "have provided" to "will provide"
and for installation instructions, maybe say "proposed installation steps"
since when you share this proposal, FDA won't receive the actual codes etc
maybe just make it a bit more clear that this is a "pre-inform" document to show them how the submission may look like, and to get their input

```

**Comment by laxamanaj** [comment] 2022-12-01 05:49
Per Ning, I have made the updates to the language of the proposal to note that these are indeed only 'proposed' steps for installation and execution.  This should make it clear that this document should just be used as a 'pre-inform' and that we would also like to openly accept any further input from them to update/finalize this proposal any further. 

[pilot3-adam-fda-execution-proposal.docx](https://github.com/RConsortium/submissions-pilot3-adam/files/10129540/pilot3-adam-fda-execution-proposal.docx)

@thomas-neitmann let me know if you have any further comments by tomorrow.  Also feel free to update on your end if needed and re-attach updated version to save time.  As Joe mentioned, this shouldn't be too formal to discuss during the meeting, but assume we will deliver to FDA staff shortly after the meeting this Friday.

Best,
Joel

**Comment by thomas-neitmann** [comment] 2022-12-01 14:02
Thanks a lot for putting this together @laxamanaj. I made some adjustments and left one comment which is an action item to address.

Btw, let's use a gdoc next time for easier collaborative writing.

[pilot3-adam-fda-execution-proposal.docx](https://github.com/RConsortium/submissions-pilot3-adam/files/10132992/pilot3-adam-fda-execution-proposal.docx)

**Comment by laxamanaj** [comment] 2022-12-01 17:41
Thanks, @thomas-neitmann .  Absolutely, I was going to use gDoc initially, but had issues with formatting, so I forged ahead using word.  Point taken. :)  Thank you!

**Comment by laxamanaj** [comment] 2022-12-02 04:37
Many thanks again, @thomas-neitmann for your comments and feedback.  All made sense to me and your comments allowed me to update the language accordingly.  This is now the initial draft we can submit to the FDA as a proposal and what we will share in the meeting tomorrow.  

[pilot3-adam-fda-execution-proposal_01Dec2022.pdf](https://github.com/RConsortium/submissions-pilot3-adam/files/10138117/pilot3-adam-fda-execution-proposal_01Dec2022.pdf)
[pilot3-adam-fda-execution-proposal_01Dec2022.docx](https://github.com/RConsortium/submissions-pilot3-adam/files/10138119/pilot3-adam-fda-execution-proposal_01Dec2022.docx)

Best,
Joel

**Comment by robertdevine** [comment] 2022-12-02 17:37
Anticipating the Pilot 4 containers for whichever runtime, for the system-level configuration:
https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html
https://www.msys2.org/

**Comment by kaz462** [comment] 2022-12-02 17:49
Thanks, @laxamanaj for this document! 
minor issue regarding the dataset name: `adas.xpt` in the document, but the dataset under `adam\` folder is  `adadas.xpt`.
Please also suggest the program name: `ad_adas.R` in the document vs  current `adadas.R`

**Comment by thomas-neitmann** [comment] 2022-12-05 11:05
> ADaM program names should not be prefixed with ad_ as @kaz462 mentions.

 Agree.

> If you intend to submit the programs as they are should we then not ensure lowercase .r instead of .R?

Convention is to use `.R`. Is there a requirement from FDA to have lowecase file extensions? If so, then yes let's switch to `.r` instead.

> AE Time to 1st Derm. Event Analysis -> The AE in front is not clear. Could we clarify? Time to Event analysis: Time to first Dermatological Event

This is the dataset label which is restricted to 40 characters as we're still using `.xpt` for submission 😔 I

**Comment by laxamanaj** [comment] 2022-12-07 16:59
Thanks for the feedback.

I've udpated the programs names without the `ad_` prefix.

I'll leave as `.R` for now as I've read that it is just a convention.  But upper or lowercase may not make a difference.

Yeah, unfortunately, since we should be CDISC compliant dataset labels have to be 40 characters or less.  This seems to be the description used in the CDISC pilot as well, per the define.pdf.

The proposal will be the `submissions_wg` repo soon.  Re-attaching the udpated version here : 
[R_Submission_Pilot_3_ADaM_FDA_Execution_Proposal_02Dec2022.pdf](https://github.com/RConsortium/submissions-pilot3-adam/files/10178235/R_Submission_Pilot_3_ADaM_FDA_Execution_Proposal_02Dec2022.pdf)
[R_Submission_Pilot_3_ADaM_FDA_Execution_Proposal_02Dec2022.docx](https://github.com/RConsortium/submissions-pilot3-adam/files/10178236/R_Submission_Pilot_3_ADaM_FDA_Execution_Proposal_02Dec2022.docx)

**Comment by laxamanaj** [comment] 2023-02-11 08:16
Closing out.  Proposal now in review #37

**Closed by laxamanaj** 2023-02-11 08:16 UTC
Labels: submission process
